'use client';

import * as React from 'react';
import {
  useState,
  useRef,
  useLayoutEffect,
  useEffect,
  useCallback,
} from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import debounce from 'lodash/debounce';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { prism } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { motion, AnimatePresence } from 'framer-motion';

import { ScrollToBottomButton } from '@/components/ScrollToBottomButton';
import { ThinkDrawer } from '@/components/ThinkDrawer';
import { MermaidCodeBlock } from '@/components/MermaidCodeBlock';
import { WelcomeMessage } from '@/components/WelcomeMessage';
import { SearchingIndicator } from '@/components/SearchingIndicator';
import { Source } from '@/components/Source';
import { Loading } from '@/components/Loading';
import { Message, MessageContent, KeywordButton, ModelOption } from '@/components/types';
import { MessageList } from '../components/MessageList';

const MODEL_OPTIONS: ModelOption[] = [
  {
    id: '@tx/deepseek-ai/deepseek-r1-distill-qwen-32b',
    name: 'DeepSeek R1 Distill (32B)'
  },
  {
    id: '@tx/deepseek-ai/deepseek-r1-0528',
    name: 'DeepSeek R1 (0528)'
  },
  {
    id: '@tx/deepseek-ai/deepseek-v3-0324',
    name: 'DeepSeek V3 (0324)'
  }
];

export default function Home() {
  // 状态管理
  const [userInput, setUserInput] = useState('');
  const [useNetwork, setUseNetwork] = useState(false);
  const [showKeywords, setShowKeywords] = useState(true);
  const [isMobile, setIsMobile] = useState(false);
  const [isClient, setIsClient] = useState(false);
  const [answered, setAnswered] = useState(false);
  const [isSearching, setIsSearching] = useState(false);
  const [isSiteEnv, setIsSiteEnv] = useState(false);
  const [isStreaming, setIsStreaming] = useState(false);
  const [selectedModel, setSelectedModel] = useState('@tx/deepseek-ai/deepseek-v3-0324');
  const [showScrollButton, setShowScrollButton] = useState(false);
  const [isDarkMode, setIsDarkMode] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  
  // refs
  const messageRef = useRef<HTMLDivElement>(null);
  const abortControllerRef = useRef<AbortController | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    setIsSiteEnv(window.location.href.includes('.site'));
    setIsClient(true);
  }, []);
  
  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [isDarkMode]);

  const scrollToBottom = () => {
    if (messageRef.current) {
      messageRef.current.scrollTo({
        top: messageRef.current.scrollHeight,
        behavior: 'smooth'
      });
    }
  };

  const t = (en: string) => {
    const map: { [key: string]: string } = {
      'How to write Amazon product titles for wireless earphones with ANC and 40h battery life?':
        '为带有主动降噪和40小时续航的无线耳机写产品标题',
      'Generate a professional email template to handle customer complaints about product quality':
        '生成一个处理产品质量客户投诉的专业邮件模板',
      'Help optimize Python code for quick sort algorithm with time complexity analysis':
        '帮助优化快速排序算法的Python代码并分析时间复杂度',
      'Create a comparison table of marketing strategies between TikTok and Instagram Reels':
        '创建抖音和Instagram Reels营销策略的对比表',
      'DeepSeek 671B on the Edge': 'DeepSeek 671B 边缘计算',
      'EdgeOne AI is transforming user experience and operational efficiency by performing AI computations closer to end-users, ensuring ultra-low latency and consistently high performance.':
        'EdgeOne AI 通过在靠近终端用户的地方执行 AI 计算，提升用户体验和运营效率，确保超低延迟和稳定的高性能。',
      'Available for free on ': '免费使用 ',
      'Thinking Process': '思考过程',
      Processing: '处理中',
      'Generated by EdgeOne AI': '由 EdgeOne AI 生成',
      'Type a message...': '输入消息...',
      'Network: On': '联网: 开启',
      'Network: Off': '联网: 关闭',
      References: '参考',
      Stop: '停止',
      'Model': '模型',
      'DeepSeek R1 Distill (32B)': 'DeepSeek R1 Distill (32B)',
      'DeepSeek R1 (0528)': 'DeepSeek R1 (0528)',
      'DeepSeek V3 (0324)': 'DeepSeek V3 (0324)',
    };
    return isSiteEnv ? map[en] || en : en;
  };

  const KEYWORD_BUTTONS: KeywordButton[] = [
    {
      text: t(
        'How to write Amazon product titles for wireless earphones with ANC and 40h battery life?'
      ),
      query: t(
        'How to write Amazon product titles for wireless earphones with ANC and 40h battery life?'
      ),
    },
    {
      text: t(
        'Generate a professional email template to handle customer complaints about product quality'
      ),
      query: t(
        'Generate a professional email template to handle customer complaints about product quality'
      ),
    },
    {
      text: t(
        'Help optimize Python code for quick sort algorithm with time complexity analysis'
      ),
      query: t(
        'Help optimize Python code for quick sort algorithm with time complexity analysis'
      ),
    },
    {
      text: t(
        'Create a comparison table of marketing strategies between TikTok and Instagram Reels'
      ),
      query: t(
        'Create a comparison table of marketing strategies between TikTok and Instagram Reels'
      ),
    },
  ];

  useLayoutEffect(() => {
    setIsClient(true);
    setIsMobile(window.innerWidth < 640);

    const handleResize = () => {
      setIsMobile(window.innerWidth < 640);
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);



  const getDisplayButtons = () => {
    if (isMobile) {
      const randomIndex = Math.floor(Math.random() * KEYWORD_BUTTONS.length);
      return [KEYWORD_BUTTONS[randomIndex]];
    }
    return KEYWORD_BUTTONS;
  };

  useEffect(() => {
    const handleScroll = () => {
      if (messageRef.current) {
        const { scrollTop, scrollHeight, clientHeight } = messageRef.current;
        const windowHeight = window.innerHeight;
        const contentExceeds70Percent = scrollHeight > windowHeight * 0.7;
        const distanceFromBottom = scrollHeight - (scrollTop + clientHeight);
        const isAtBottom = distanceFromBottom <= 20;
        
        setShowScrollButton(contentExceeds70Percent && !isAtBottom);
      }
    };

    if (messageRef.current) {
      messageRef.current.addEventListener('scroll', handleScroll);
      const resizeObserver = new ResizeObserver(() => {
        handleScroll();
      });
      resizeObserver.observe(messageRef.current);

      handleScroll();

      return () => {
        if (messageRef.current) {
          messageRef.current.removeEventListener('scroll', handleScroll);
        }
        resizeObserver.disconnect();
      };
    }
  }, [messages]);

  const handleKeywordClick = (query: string) => {
    setUserInput(query);
    setShowKeywords(false);
    setTimeout(() => {
      handleSubmit({ preventDefault: () => {} } as React.FormEvent);
    });
  };

  const debouncedUpdateMessage = useCallback(
    debounce((updateFn: (prev: Message[]) => Message[]) => {
      setMessages(updateFn);
    }, 50),
    []
  );

  const processStreamResponse = async (
    response: Response,
    updateMessage: (content: MessageContent) => void
  ) => {
    const contentType = response.headers.get('content-type');
    if (contentType && contentType.includes('application/json')) {
      setIsSearching(false);
      const errorData = await response.json();
      return updateMessage({
        content:
          errorData?.error || 'Sorry, something went wrong. Please try again.',
      });
    }

    const reader = response.body!.getReader();
    const decoder = new TextDecoder();
    let buffer = '';

    let accumulatedContent = '';
    let accumulatedThink = '';
    let thinking = false;

    setIsStreaming(true);

    try {
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split('\n');
        buffer = lines.pop() || '';

        for (const line of lines) {
          if (
            !line.trim() ||
            line.includes('[DONE]') ||
            !line.includes('data: ')
          )
            continue;
          try {
            const json = JSON.parse(line.replace(/^data: /, ''));
            const token = json.choices[0]?.delta?.content || '';
            const reasoningToken =
              json.choices[0]?.delta?.reasoning_content || '';

            // Turn off searching indicator when first token arrives
            if (isSearching) {
              setIsSearching(false);
            }

            // Handle think content
            if (
              token.includes('<think>') ||
              token.includes('\u003cthink\u003e')
            ) {
              thinking = true;
              continue;
            }
            if (
              token.includes('</think>') ||
              token.includes('\u003c/think\u003e')
            ) {
              thinking = false;
              continue;
            }

            if (thinking || reasoningToken) {
              accumulatedThink += token || reasoningToken || '';
            } else {
              accumulatedContent += token || '';
            }

            updateMessage({
              content: accumulatedContent,
              think: accumulatedThink,
            });
          } catch (e) {
            console.error('Failed to parse chunk:', e);
          }
        }
      }
    } catch (error: unknown) {
      if (error instanceof Error && error.name === 'AbortError') {
        console.log('Stream aborted by user');
      } else {
        console.error('Stream error:', error);
      }
    } finally {
      setIsStreaming(false);
    }
  };

  const handleStopResponse = () => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort();
      abortControllerRef.current = null;
      setIsLoading(false);
      setIsStreaming(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!userInput.trim() || isLoading) return;

    // If already streaming, stop the current response
    if (isStreaming) {
      handleStopResponse();
      return;
    }

    setShowKeywords(false);
    setIsLoading(true);
    setIsSearching(true);
    const currentInput = textareaRef.current?.value || '';
    setUserInput('');

    // Create conversation history
    let conversationHistory = [...messages];

    if (messages[0]?.role === 'assistant') {
      setMessages([]);
      conversationHistory = [];
    }

    // Add new user message
    conversationHistory.push({ role: 'user', content: currentInput });

    // Add empty assistant message that will be streamed
    setMessages([...conversationHistory, { role: 'assistant', content: '' }]);

    setTimeout(() => {
      messageRef.current?.scrollTo(0, messageRef.current?.scrollHeight);
    }, 300);

    try {
      const url =
        process.env.NODE_ENV === 'development'
          ? process.env.NEXT_PUBLIC_BASE_URL!
          : '/v1/chat/completions';

      // Create a new AbortController for this request
      abortControllerRef.current = new AbortController();
      const signal = abortControllerRef.current.signal;

      const res = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messages: conversationHistory.map((msg) => ({
            role: msg.role,
            content: msg.content,
          })),
          network: useNetwork,
          model: selectedModel,
        }),
        signal, // Attach the signal to the fetch request
      });

      if (!res.ok) {
        throw new Error(res.statusText);
      }

      setAnswered(true);

      let source: { url: string; title: string }[] = [];
      res.headers.forEach((value, name) => {
        if (name === 'results') {
          const results = JSON.parse(value);
          source = results.map((result: { url: string; title: string }) => {
            return {
              url: result.url,
              title: decodeURIComponent(result.title),
            };
          });
        }
      });

      setMessages((prev) => {
        const newMessages = structuredClone(prev);
        const lastMessage = newMessages[newMessages.length - 1];
        lastMessage.source = source;
        return newMessages;
      });

      await processStreamResponse(res, (_content: MessageContent) => {
        debouncedUpdateMessage((prev) => {
          const newMessages = structuredClone(prev);
          const lastMessage = newMessages[newMessages.length - 1];

          if (_content.think) {
            lastMessage.think = _content.think;
          }
          if (_content.content) {
            lastMessage.content = _content.content;
          }

          return newMessages;
        });
      });
    } catch (error: unknown) {
      if (!(error instanceof Error) || error.name !== 'AbortError') {
        console.error('Error:', error);
        setMessages((prev) => [
          ...prev.slice(0, -1),
          {
            role: 'assistant',
            content: 'Sorry, something went wrong. Please try again.',
          },
        ]);
      }
    } finally {
      setIsLoading(false);
      abortControllerRef.current = null;
    }
  };

  const handleTextareaChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setUserInput(e.target.value);
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }
  };

  return (
    isClient && (
      <div className="flex flex-col h-screen">
        {/* 顶部栏 */}
        <header className="sticky top-0 z-40 backdrop-blur-md bg-white/80 dark:bg-gray-900/80 border-b border-gray-100 dark:border-gray-800">
          <div className="container flex items-center justify-between h-16 px-4 mx-auto">
            <div className="flex items-center space-x-3">
              <div className="relative">
                <div className="absolute -inset-1 bg-gradient-to-r from-blue-600 to-indigo-600 rounded-full blur-sm opacity-30"></div>
                <div className="relative">
                  <h1 className="text-xl font-bold text-gradient from-blue-600 to-indigo-600 dark:from-blue-400 dark:to-indigo-400">智能对话助手</h1>
                </div>
              </div>
            </div>
            
            <button
              onClick={() => setIsDarkMode(!isDarkMode)}
              className="p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
              aria-label={isDarkMode ? "切换到亮色模式" : "切换到暗色模式"}
            >
              {isDarkMode ? (
                <svg className="w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
                </svg>
              ) : (
                <svg className="w-5 h-5 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
                </svg>
              )}
            </button>
          </div>
        </header>

        <main className="flex-1 overflow-hidden">
          <div className="container h-full mx-auto px-4">
            <WelcomeMessage show={showKeywords} t={t} />
            
            <div className="h-[calc(100vh-13rem)] md:h-[calc(100vh-14rem)] overflow-hidden">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="h-full glass rounded-2xl overflow-hidden"
              >
                <div 
                  ref={messageRef} 
                  className="h-full px-4 py-6 overflow-y-auto md:px-6 scrollbar-hidden"
                >
                  <MessageList messages={messages} isSearching={isSearching} t={t} />
                </div>
              </motion.div>
            </div>
          </div>
        </main>

        {showKeywords && (
          <div className="container mx-auto px-4 mt-4">
            <div className="max-w-3xl mx-auto mb-6">
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                {getDisplayButtons().map((button) => (
                  <motion.button
                    key={button.text}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3 }}
                    onClick={() => handleKeywordClick(button.query)}
                    className="px-4 py-3 text-sm text-left text-gray-700 dark:text-gray-200 transition-all duration-200 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl hover:shadow-md hover:border-blue-300 dark:hover:border-blue-700 hover:bg-blue-50 dark:hover:bg-blue-900/30"
                  >
                    {button.text}
                  </motion.button>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Scroll to bottom button */}
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto pb-2">
            <ScrollToBottomButton 
              isVisible={showScrollButton} 
              onClick={scrollToBottom} 
            />
          </div>
        </div>

        {/* Input section */}
        <div className="container mx-auto px-4 pb-6">
          <form onSubmit={handleSubmit} className="max-w-3xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
              className="glass rounded-2xl overflow-hidden shadow-lg"
            >
              <textarea
                ref={textareaRef}
                value={userInput}
                onChange={handleTextareaChange}
                placeholder={t('Type a message...')}
                disabled={isLoading}
                className={`w-full bg-transparent text-gray-800 dark:text-gray-100 px-5 py-4 focus:outline-none focus:ring-0 resize-none min-h-[60px] max-h-[200px] placeholder:text-gray-400 dark:placeholder:text-gray-500 border-none text-base ${
                  isLoading ? 'cursor-not-allowed opacity-50' : ''
                }`}
                onCompositionStart={(e) => {
                  (e.target as HTMLTextAreaElement).dataset.composing = 'true';
                }}
                onCompositionEnd={(e) => {
                  (e.target as HTMLTextAreaElement).dataset.composing = 'false';
                }}
                onKeyDown={(e) => {
                  const target = e.target as HTMLTextAreaElement;
                  const isComposing = target.dataset.composing === 'true';
                  if (e.key === 'Enter' && !e.shiftKey && !isComposing) {
                    e.preventDefault();
                    handleSubmit(e);
                  }
                }}
              />
              <div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 border-t border-gray-100 dark:border-gray-800 bg-white/50 dark:bg-gray-800/50">
                <div className="flex flex-wrap items-center gap-3">
                  <div className="relative">
                    <select
                      value={selectedModel}
                      onChange={(e) => setSelectedModel(e.target.value)}
                      className="pl-3 pr-8 py-2 text-sm bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/50 min-w-[180px] appearance-none w-full cursor-pointer"
                      disabled={isLoading}
                    >
                      {MODEL_OPTIONS.map((model) => (
                        <option key={model.id} value={model.id}>
                          {t(model.name)}
                        </option>
                      ))}
                    </select>
                    <div className="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                      <svg className="w-4 h-4 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
                      </svg>
                    </div>
                  </div>
                  <button
                    type="button"
                    onClick={() => setUseNetwork(!useNetwork)}
                    className={`flex items-center px-3 py-2 rounded-lg text-sm transition-all ${
                      useNetwork
                        ? 'bg-gradient-to-r from-blue-500/10 to-indigo-500/10 text-blue-600 dark:text-blue-400 border border-blue-200 dark:border-blue-800'
                        : 'bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-300 border border-gray-200 dark:border-gray-700'
                    }`}
                  >
                    <svg
                      className="w-4 h-4 mr-1.5"
                      fill="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z" />
                    </svg>
                    {useNetwork ? t('Network: On') : t('Network: Off')}
                  </button>
                </div>
                <button
                  type={isStreaming ? 'button' : 'submit'}
                  onClick={isStreaming ? handleStopResponse : undefined}
                  disabled={
                    (isLoading && !isStreaming) ||
                    (!userInput.trim() && !isStreaming)
                  }
                  className={`flex items-center justify-center w-10 h-10 rounded-full transition-all duration-300 ${
                    (isLoading && !isStreaming) ||
                    (!userInput.trim() && !isStreaming)
                      ? 'bg-gray-100 dark:bg-gray-800 text-gray-400 dark:text-gray-600 cursor-not-allowed'
                      : isStreaming
                      ? 'bg-gradient-to-r from-red-500 to-pink-600 text-white shadow-lg hover:shadow-red-500/25 active:scale-95'
                      : 'bg-gradient-to-r from-blue-500 to-indigo-600 text-white shadow-lg hover:shadow-blue-500/25 active:scale-95'
                  }`}
                >
                  {isStreaming ? (
                    <svg
                      className="w-5 h-5"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                    >
                      <path
                        fillRule="evenodd"
                        d="M10 18a8 8 0 100-16 8 8 0 000 16zM8 7a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1V8a1 1 0 00-1-1H8z"
                        clipRule="evenodd"
                      />
                    </svg>
                  ) : (
                    <svg
                      className="w-5 h-5"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 12h14m-4 4l4-4-4-4"
                      />
                    </svg>
                  )}
                </button>
              </div>
            </motion.div>
          </form>
        </div>
      </div>
    )
  );
}
